package io.github.firestormfmd.scenescripter.core.anim;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Predicate;

import io.github.firestormfmd.scenescripter.core.math.CubicBezier;

/**
 * One animatable value: a default plus keyframes sorted by tick, at most one per tick.
 */
public final class Channel<T> {
	private final ValueType<T> type;
	private T defaultValue;
	private final List<Keyframe<T>> keys = new ArrayList<>();

	public Channel(ValueType<T> type, T defaultValue) {
		this.type = Objects.requireNonNull(type, "type");
		this.defaultValue = type.cast(defaultValue);
	}

	public ValueType<T> type() {
		return type;
	}

	public T defaultValue() {
		return defaultValue;
	}

	public void setDefaultValue(T value) {
		this.defaultValue = type.cast(value);
	}

	public List<Keyframe<T>> keys() {
		return Collections.unmodifiableList(keys);
	}

	public boolean isEmpty() {
		return keys.isEmpty();
	}

	public Optional<Keyframe<T>> keyAt(int tick) {
		int i = indexOf(tick);
		return i >= 0 ? Optional.of(keys.get(i)) : Optional.empty();
	}

	/**
	 * Adds a keyframe, replacing any keyframe already at that tick.
	 *
	 * @return the keyframe that was replaced, if any
	 */
	public Optional<Keyframe<T>> put(Keyframe<T> key) {
		type.cast(key.value());
		int i = indexOf(key.tick());
		if (i >= 0) {
			return Optional.of(keys.set(i, key));
		}
		keys.add(-i - 1, key);
		return Optional.empty();
	}

	/** Like {@link #put} for keyframes whose type is only known at runtime, such as ones read back from an edit. */
	@SuppressWarnings("unchecked")
	public Optional<Keyframe<T>> putUnchecked(Keyframe<?> key) {
		type.cast(key.value());
		return put((Keyframe<T>) key);
	}

	public Optional<Keyframe<T>> remove(int tick) {
		int i = indexOf(tick);
		return i >= 0 ? Optional.of(keys.remove(i)) : Optional.empty();
	}

	/** Removes every keyframe matching the filter, such as all keyframes generated by one event. */
	public List<Keyframe<T>> removeIf(Predicate<Keyframe<T>> filter) {
		List<Keyframe<T>> removed = new ArrayList<>();
		keys.removeIf(k -> {
			if (filter.test(k)) {
				removed.add(k);
				return true;
			}
			return false;
		});
		return removed;
	}

	public Channel<T> copy() {
		Channel<T> c = new Channel<>(type, defaultValue);
		c.keys.addAll(keys);
		return c;
	}

	/**
	 * Value at a (possibly fractional) tick. Before the first keyframe the first value holds, after the last the
	 * last value holds, and with no keyframes the default applies.
	 */
	public T valueAt(double tick) {
		if (keys.isEmpty()) {
			return defaultValue;
		}
		int i = lastIndexAtOrBefore(tick);
		if (i < 0) {
			return keys.getFirst().value();
		}
		Keyframe<T> k0 = keys.get(i);
		if (i == keys.size() - 1 || tick == k0.tick()) {
			return k0.value();
		}
		Keyframe<T> k1 = keys.get(i + 1);
		if (!type.interpolates() || k0.interpolation() == Interpolation.STEP) {
			return k0.value();
		}

		double[] c0 = type.toComponents().apply(k0.value());
		double[] c1 = type.toComponents().apply(k1.value());
		double[] out = new double[c0.length];

		if (k0.interpolation() == Interpolation.BEZIER) {
			for (int c = 0; c < out.length; c++) {
				out[c] = bezierComponent(i, c, tick);
			}
		} else {
			double s = (tick - k0.tick()) / (k1.tick() - k0.tick());
			double e = k0.interpolation().ease(s);
			for (int c = 0; c < out.length; c++) {
				out[c] = c0[c] + (c1[c] - c0[c]) * e;
			}
		}
		return type.fromComponents().apply(out);
	}

	private double bezierComponent(int i, int component, double tick) {
		Keyframe<T> k0 = keys.get(i);
		Keyframe<T> k1 = keys.get(i + 1);
		double t0 = k0.tick();
		double t1 = k1.tick();
		double span = t1 - t0;
		double v0 = component(k0, component);
		double v1 = component(k1, component);

		double outDt;
		double outDv;
		double inDt;
		double inDv;
		boolean custom = type.components() == 1;
		if (custom && k0.handles() != null) {
			outDt = clamp(k0.handles().outDt(), 0, span);
			outDv = k0.handles().outDv();
		} else {
			outDt = span / 3;
			outDv = autoSlope(i, component) * outDt;
		}
		if (custom && k1.handles() != null) {
			inDt = clamp(k1.handles().inDt(), -span, 0);
			inDv = k1.handles().inDv();
		} else {
			inDt = -span / 3;
			inDv = autoSlope(i + 1, component) * inDt;
		}

		double u = solveBezierTime(t0, t0 + outDt, t1 + inDt, t1, tick);
		return CubicBezier.value(v0, v0 + outDv, v1 + inDv, v1, u);
	}

	/**
	 * Automatic handle slope: flat at the ends and at peaks and dips (so curves never overshoot a keyframe),
	 * otherwise the slope between the neighbouring keyframes.
	 */
	private double autoSlope(int i, int component) {
		if (i <= 0 || i >= keys.size() - 1) {
			return 0;
		}
		double prev = component(keys.get(i - 1), component);
		double cur = component(keys.get(i), component);
		double next = component(keys.get(i + 1), component);
		if ((cur >= prev && cur >= next) || (cur <= prev && cur <= next)) {
			return 0;
		}
		return (next - prev) / (keys.get(i + 1).tick() - keys.get(i - 1).tick());
	}

	private double component(Keyframe<T> key, int component) {
		return type.toComponents().apply(key.value())[component];
	}

	/**
	 * Finds the curve parameter where the time curve reaches {@code target}. Handles are clamped inside the
	 * segment, so the time curve only ever increases and bisection always converges.
	 */
	private static double solveBezierTime(double x0, double x1, double x2, double x3, double target) {
		double lo = 0;
		double hi = 1;
		for (int iter = 0; iter < 60; iter++) {
			double mid = (lo + hi) / 2;
			if (CubicBezier.value(x0, x1, x2, x3, mid) < target) {
				lo = mid;
			} else {
				hi = mid;
			}
		}
		return (lo + hi) / 2;
	}

	private static double clamp(double v, double min, double max) {
		return Math.max(min, Math.min(max, v));
	}

	/** Binary search by tick: index if found, otherwise {@code -(insertionPoint) - 1}. */
	private int indexOf(int tick) {
		int lo = 0;
		int hi = keys.size() - 1;
		while (lo <= hi) {
			int mid = (lo + hi) >>> 1;
			int t = keys.get(mid).tick();
			if (t < tick) {
				lo = mid + 1;
			} else if (t > tick) {
				hi = mid - 1;
			} else {
				return mid;
			}
		}
		return -(lo + 1);
	}

	private int lastIndexAtOrBefore(double tick) {
		int lo = 0;
		int hi = keys.size() - 1;
		int result = -1;
		while (lo <= hi) {
			int mid = (lo + hi) >>> 1;
			if (keys.get(mid).tick() <= tick) {
				result = mid;
				lo = mid + 1;
			} else {
				hi = mid - 1;
			}
		}
		return result;
	}
}
